name: release-build

on:
  push:
    tags:
      - '*'

permissions:
  contents: read
  packages: write

jobs:
  publish-release:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: winterjung/split@v2
        id: split
        with:
          separator: '-'
          msg: ${{ github.ref_name }}
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: wrapper
      - name: Execute Gradle build
        id: build
        env:
          PACKAGES_TOKEN: ${{ secrets.ALP_ACC_SVC_CI_TOKEN }}
          GITHUB_USERNAME: "ALP-ACC-SVC-Github"
          GITHUB_TOKEN: ${{ secrets.ALP_ACC_SVC_CI_TOKEN }}
        run: |
          ./gradlew ${{ steps.split.outputs._0 }}:build
#      - name: publish
#        env:
#          PACKAGES_TOKEN: ${{ secrets.ALP_ACC_SVC_CI_TOKEN }}
#          GITHUB_USERNAME: "ALP-ACC-SVC-Github"
#          GITHUB_TOKEN: ${{ secrets.ALP_ACC_SVC_CI_TOKEN }}
#        run: |
#          ./gradlew ${{ steps.split.outputs._0 }}:publish
